<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $indie = Category::where('slug', 'indie')->first();
        $postPunk = Category::where('slug', 'post-punk')->first();
        $electronic = Category::where('slug', 'electronic')->first();
        $rock = Category::where('slug', 'rock')->first();
        $folk = Category::where('slug', 'folk')->first();
        $pop = Category::where('slug', 'pop')->first();

        $products = [
            // Featured Products - Using Figma images
            [
                'title' => 'Demon Days',
                'artist' => 'Gorillaz',
                'slug' => 'gorillaz-demon-days',
                'description' => 'Gorillaz\'s 2005 masterpiece featuring the iconic "Feel Good Inc." and "DARE". Damon Albarn\'s virtual band delivers a dark, cinematic journey through post-apocalyptic soundscapes.',
                'archivist_note' => 'Parlophone 2xLP reissue on 180g vinyl. The animated artwork is faithfully reproduced on gatefold sleeve. This pressing captures the album\'s layered production beautifully.',
                'price' => 34.99,
                'category_id' => $electronic->id,
                'year' => '2005',
                'label' => 'Parlophone',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Intro', 'Last Living Souls', 'Kids with Guns', 'O Green World'],
                    'b' => ['Dirty Harry', 'Feel Good Inc.', 'El Mañana', 'Every Planet We Reach Is Dead'],
                    'c' => ['November Has Come', 'All Alone', 'White Light', 'DARE'],
                    'd' => ['Fire Coming Out of the Monkey\'s Head', 'Don\'t Get Lost in Heaven', 'Demon Days'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/vinyl-gorillaz.png',
            ],
            [
                'title' => '24K Magic',
                'artist' => 'Bruno Mars',
                'slug' => 'bruno-mars-24k-magic',
                'description' => 'Bruno Mars\' 2016 funk-driven album that dominated the Grammys. A throwback to 80s and 90s R&B with modern production polish.',
                'archivist_note' => 'Atlantic Records pressing on standard black vinyl. The bass-heavy tracks translate perfectly to vinyl - "24K Magic" and "Chunky" hit with incredible warmth.',
                'price' => 29.99,
                'category_id' => $pop->id,
                'year' => '2016',
                'label' => 'Atlantic',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['24K Magic', 'Chunky', 'Perm', 'That\'s What I Like'],
                    'b' => ['Versace on the Floor', 'Straight Up & Down', 'Calling All My Lovelies', 'Finesse', 'Too Good to Say Goodbye'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/vinyl-bruno-mars.png',
            ],
            [
                'title' => 'Violator',
                'artist' => 'Depeche Mode',
                'slug' => 'depeche-mode-violator',
                'description' => 'Depeche Mode\'s 1990 commercial breakthrough. "Personal Jesus" and "Enjoy the Silence" became defining tracks of the era. Dark, seductive synth-pop perfection.',
                'archivist_note' => 'Mute Records 180g remaster. The analog synths sound incredible on vinyl - this pressing captures every layer of Alan Wilder\'s intricate production.',
                'price' => 32.99,
                'category_id' => $electronic->id,
                'year' => '1990',
                'label' => 'Mute',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['World in My Eyes', 'Sweetest Perfection', 'Personal Jesus', 'Halo', 'Waiting for the Night'],
                    'b' => ['Enjoy the Silence', 'Policy of Truth', 'Blue Dress', 'Clean'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 3,
                'image' => '/images/figma/vinyl-depeche-mode.png',
            ],
            [
                'title' => 'Kind of Blue',
                'artist' => 'Miles Davis',
                'slug' => 'miles-davis-kind-of-blue',
                'description' => 'The best-selling jazz album of all time. Miles Davis\'s 1959 masterpiece introduced modal jazz to the world. Featuring John Coltrane, Bill Evans, and Cannonball Adderley.',
                'archivist_note' => 'Columbia/Legacy 180g pressing from original master tapes. The warmth and intimacy of this recording is legendary - vinyl is the definitive way to experience it.',
                'price' => 29.99,
                'category_id' => $folk->id, // Using folk as closest to jazz
                'year' => '1959',
                'label' => 'Columbia',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['So What', 'Freddie Freeloader', 'Blue in Green'],
                    'b' => ['All Blues', 'Flamenco Sketches'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 6,
                'image' => '/images/figma/vinyl-miles-davis.png',
            ],
            [
                'title' => 'The Great War',
                'artist' => 'Sabaton',
                'slug' => 'sabaton-the-great-war',
                'description' => 'Swedish power metal band Sabaton\'s 2019 concept album about World War I. Epic, historically-themed metal with anthemic choruses and thundering riffs.',
                'archivist_note' => 'Nuclear Blast pressing on black vinyl. The production is massive - guitars are crisp, drums are thunderous. A must for metal collectors.',
                'price' => 27.99,
                'category_id' => $rock->id,
                'year' => '2019',
                'label' => 'Nuclear Blast',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['The Future of Warfare', 'Seven Pillars of Wisdom', '82nd All the Way', 'The Attack of the Dead Men', 'Devil Dogs'],
                    'b' => ['The Red Baron', 'Great War', 'A Ghost in the Trenches', 'Fields of Verdun', 'The End of the War to End All Wars', 'In Flanders Fields'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/vinyl-sabaton.png',
            ],
            [
                'title' => 'Pure Heroine',
                'artist' => 'Lorde',
                'slug' => 'lorde-pure-heroine-cd',
                'description' => 'Lorde\'s 2013 debut that made her a global star at 16. "Royals" and "Team" defined a new sound - minimalist pop with lyrical depth beyond her years.',
                'archivist_note' => 'Universal Music CD with extended booklet. The sparse production sounds pristine on CD. A landmark debut album.',
                'price' => 14.99,
                'category_id' => $pop->id,
                'year' => '2013',
                'label' => 'Universal',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Tennis Court', '400 Lux', 'Royals', 'Ribs', 'Buzzcut Season', 'Team', 'Glory and Gore', 'Still Sane', 'White Teeth Teens', 'A World Alone'],
                ],
                'is_featured' => true,
                'is_new_arrival' => false,
                'stock' => 8,
                'image' => '/images/figma/cd-lorde.png',
            ],

            // New Arrivals
            [
                'title' => 'Hello World',
                'artist' => 'Joy (Red Velvet)',
                'slug' => 'joy-hello-world-cd',
                'description' => 'Red Velvet member Joy\'s solo debut. A refreshing blend of retro pop and modern K-pop sensibilities with her signature warm vocals.',
                'archivist_note' => 'SM Entertainment Korean pressing with photobook and photocards. Limited edition packaging.',
                'price' => 24.99,
                'category_id' => $pop->id,
                'year' => '2024',
                'label' => 'SM Entertainment',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Hello', 'Day By Day', 'If Only', 'Happy Birthday To You', 'Be There For You', 'Je T\'aime'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 4,
                'image' => '/images/figma/cd-joy-redvelvet.png',
            ],
            [
                'title' => 'Hazte Sentir',
                'artist' => 'Laura Pausini',
                'slug' => 'laura-pausini-hazte-sentir-cd',
                'description' => 'Italian pop icon Laura Pausini\'s Spanish-language album. Powerful ballads and upbeat tracks showcasing her incredible vocal range.',
                'archivist_note' => 'Warner Music CD with Spanish lyrics booklet. Beautiful vocal performances throughout.',
                'price' => 16.99,
                'category_id' => $pop->id,
                'year' => '2018',
                'label' => 'Warner Music',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Hazte Sentir', 'Fantastico (Haz Lo Que Eres)', 'He Creido En Mi', 'Verdades a Medias', 'Nuevo', 'Nadie Ha Dicho', 'Frasi a Meta', 'Innamorata', '200 Notas', 'El Valor de Seguir Adelante', 'Mi Tengo', 'Sono Solo Nuvole'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 5,
                'image' => '/images/figma/cd-laura-pausini.png',
            ],
            [
                'title' => 'Messy',
                'artist' => 'Olivia Dean',
                'slug' => 'olivia-dean-messy-cd',
                'description' => 'British soul singer Olivia Dean\'s debut album. Warm, intimate R&B with jazz influences and deeply personal songwriting.',
                'archivist_note' => 'Island Records CD. Her voice is stunning - the production lets every nuance shine through.',
                'price' => 15.99,
                'category_id' => $pop->id,
                'year' => '2023',
                'label' => 'Island Records',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['The Hardest Part', 'Dive', 'UFO', 'Ladies Room', 'Carmen', 'Danger', 'Slowly', 'Messy', 'Absolute', 'The Gospel According to the Altar', 'Ok Love You Bye'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 6,
                'image' => '/images/figma/cd-olivia-dean.png',
            ],
            [
                'title' => 'Golden Hour',
                'artist' => 'ATEEZ',
                'slug' => 'ateez-golden-hour-cd',
                'description' => 'K-pop group ATEEZ\'s dynamic album featuring their signature blend of powerful choreography-ready anthems and emotional ballads.',
                'archivist_note' => 'KQ Entertainment Korean import with photobook, photocards, and poster. Collector\'s edition.',
                'price' => 29.99,
                'category_id' => $pop->id,
                'year' => '2024',
                'label' => 'KQ Entertainment',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Golden Hour', 'Work', 'Empty Box', 'Blind', 'BOUNCY', 'It\'s You', 'Youth', 'Blue Summer'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 3,
                'image' => '/images/figma/cd-ateez.png',
            ],
            [
                'title' => 'Tha Doggfather',
                'artist' => 'Snoop Dogg',
                'slug' => 'snoop-dogg-tha-doggfather-cd',
                'description' => 'Snoop Dogg\'s 1996 sophomore album. G-funk production with smooth West Coast flows. Features "Snoop\'s Upside Ya Head" and more.',
                'archivist_note' => 'Death Row Records original pressing. Classic West Coast hip-hop from the golden era.',
                'price' => 18.99,
                'category_id' => $rock->id, // Hip-hop closest to rock
                'year' => '1996',
                'label' => 'Death Row',
                'condition' => 'Near Mint',
                'tracklist' => [
                    'a' => ['Intro', 'Doggfather', 'Ride 4 Me', 'Up Jump tha Boogie', 'Freestyle Conversation', 'When I Grow Up', 'Snoop\'s Upside Ya Head', '(O.J.) Wake Up'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 4,
                'image' => '/images/figma/cd-snoop-dogg.png',
            ],
            [
                'title' => 'Soulfly',
                'artist' => 'Soulfly',
                'slug' => 'soulfly-soulfly-cd',
                'description' => 'Max Cavalera\'s post-Sepultura project\'s self-titled 1998 debut. Heavy tribal metal with world music influences. Featuring guest appearances from various metal legends.',
                'archivist_note' => 'Roadrunner Records original pressing. The percussion and groove are incredible - a unique blend of metal and Brazilian rhythms.',
                'price' => 14.99,
                'category_id' => $rock->id,
                'year' => '1998',
                'label' => 'Roadrunner',
                'condition' => 'Very Good Plus',
                'tracklist' => [
                    'a' => ['Eye for an Eye', 'No Hope = No Fear', 'Bleed', 'Tribe', 'Bumba', 'First Commandment', 'Bumbklaatt', 'Soulfly', 'Umbabarauma', 'Quilombo', 'Fire', 'The Song Remains Insane', 'Karmageddon'],
                ],
                'is_featured' => false,
                'is_new_arrival' => true,
                'stock' => 3,
                'image' => '/images/figma/cd-soulfly.png',
            ],

            // Additional Products
            [
                'title' => 'Daydream',
                'artist' => 'Mariah Carey',
                'slug' => 'mariah-carey-daydream-cd',
                'description' => 'Mariah Carey\'s 1995 album featuring "Fantasy" and "One Sweet Day". Pop perfection from the queen of the whistle register.',
                'archivist_note' => 'Columbia Records original pressing. Her vocals are pristine - the production is peak 90s R&B/pop.',
                'price' => 12.99,
                'category_id' => $pop->id,
                'year' => '1995',
                'label' => 'Columbia',
                'condition' => 'Very Good Plus',
                'tracklist' => [
                    'a' => ['Fantasy', 'Underneath the Stars', 'One Sweet Day', 'Open Arms', 'Always Be My Baby', 'I Am Free', 'When I Saw You', 'Long Ago', 'Melt Away', 'Forever', 'Daydream Interlude', 'Looking In'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/cd-mariah-carey.png',
            ],
            [
                'title' => 'Jazz at the Pawnshop',
                'artist' => 'Arne Domnérus',
                'slug' => 'arne-domnerus-jazz-pawnshop',
                'description' => 'Legendary 1976 live jazz recording from Stockholm. Considered one of the best-sounding jazz albums ever recorded. Audiophile reference standard.',
                'archivist_note' => 'Proprius Records audiophile pressing. The room ambience and instrument separation are extraordinary - a must for any serious vinyl collection.',
                'price' => 39.99,
                'category_id' => $folk->id,
                'year' => '1976',
                'label' => 'Proprius',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Limehouse Blues', 'Take Five', 'Jeep\'s Blues', 'Lady Be Good'],
                    'b' => ['Stuffy', 'Over the Rainbow', 'High Life', 'Barbados'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 2,
                'image' => '/images/figma/vinyl-jazz-closeup.png',
            ],
            [
                'title' => 'Plastic Beach',
                'artist' => 'Gorillaz',
                'slug' => 'gorillaz-plastic-beach',
                'description' => 'Gorillaz\'s 2010 eco-conscious concept album. Features Snoop Dogg, Lou Reed, and Mos Def. A sprawling, ambitious musical journey.',
                'archivist_note' => 'Parlophone 2xLP on 180g vinyl. Gatefold sleeve with stunning beach artwork. The orchestral arrangements sound magnificent.',
                'price' => 36.99,
                'category_id' => $electronic->id,
                'year' => '2010',
                'label' => 'Parlophone',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Orchestral Intro', 'Welcome to the World of the Plastic Beach', 'White Flag', 'Rhinestone Eyes'],
                    'b' => ['Stylo', 'Superfast Jellyfish', 'Empire Ants', 'Glitter Freeze'],
                    'c' => ['Some Kind of Nature', 'On Melancholy Hill', 'Broken', 'Sweepstakes'],
                    'd' => ['Plastic Beach', 'To Binge', 'Cloud of Unknowing', 'Pirate Jet'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/vinyl-gorillaz.png',
            ],
            [
                'title' => 'Unorthodox Jukebox',
                'artist' => 'Bruno Mars',
                'slug' => 'bruno-mars-unorthodox-jukebox',
                'description' => 'Bruno Mars\' 2012 genre-hopping second album. From reggae to rock to R&B, featuring "Locked Out of Heaven" and "When I Was Your Man".',
                'archivist_note' => 'Atlantic Records pressing. The variety of styles is impressive, and the vinyl brings warmth to every track.',
                'price' => 27.99,
                'category_id' => $pop->id,
                'year' => '2012',
                'label' => 'Atlantic',
                'condition' => 'Near Mint',
                'tracklist' => [
                    'a' => ['Young Girls', 'Locked Out of Heaven', 'Gorilla', 'Treasure', 'Moonshine'],
                    'b' => ['When I Was Your Man', 'Natalie', 'Show Me', 'Money Make Her Smile', 'If I Knew'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/vinyl-bruno-mars.png',
            ],
            [
                'title' => 'Music for the Masses',
                'artist' => 'Depeche Mode',
                'slug' => 'depeche-mode-music-for-masses',
                'description' => 'Depeche Mode\'s 1987 album that set the stage for their arena-filling success. "Never Let Me Down Again" and "Strangelove" are synth-pop landmarks.',
                'archivist_note' => 'Mute Records remaster. The darker production aesthetic began here - this pressing captures every synthesizer texture.',
                'price' => 28.99,
                'category_id' => $electronic->id,
                'year' => '1987',
                'label' => 'Mute',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Never Let Me Down Again', 'The Things You Said', 'Strangelove', 'Sacred', 'Little 15'],
                    'b' => ['Behind the Wheel', 'I Want You Now', 'To Have and to Hold', 'Nothing', 'Pimpf'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/vinyl-depeche-mode.png',
            ],
            [
                'title' => 'Bitches Brew',
                'artist' => 'Miles Davis',
                'slug' => 'miles-davis-bitches-brew',
                'description' => 'Miles Davis\'s 1970 fusion masterpiece that changed music forever. Electric jazz that influenced rock, funk, and electronic music for decades.',
                'archivist_note' => 'Columbia/Legacy 180g 2xLP reissue. The extended improvisations need vinyl\'s warmth - this is how it was meant to be heard.',
                'price' => 44.99,
                'category_id' => $folk->id,
                'year' => '1970',
                'label' => 'Columbia',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Pharaoh\'s Dance'],
                    'b' => ['Bitches Brew'],
                    'c' => ['Spanish Key', 'John McLaughlin'],
                    'd' => ['Miles Runs the Voodoo Down', 'Sanctuary'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 3,
                'image' => '/images/figma/vinyl-miles-davis.png',
            ],
            [
                'title' => 'Carolus Rex',
                'artist' => 'Sabaton',
                'slug' => 'sabaton-carolus-rex',
                'description' => 'Sabaton\'s 2012 concept album about the Swedish Empire. Available in both Swedish and English versions. Epic power metal history lessons.',
                'archivist_note' => 'Nuclear Blast 2xLP pressing. One of the band\'s finest albums - "The Lion from the North" is a standout.',
                'price' => 32.99,
                'category_id' => $rock->id,
                'year' => '2012',
                'label' => 'Nuclear Blast',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Dominium Maris Baltici', 'The Lion from the North', 'Gott Mit Uns', 'A Lifetime of War'],
                    'b' => ['Carolus Rex', 'Killing Ground', 'Poltava', 'Long Live the King', 'Ruina Imperii'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/vinyl-sabaton.png',
            ],
            [
                'title' => 'Melodrama',
                'artist' => 'Lorde',
                'slug' => 'lorde-melodrama-cd',
                'description' => 'Lorde\'s 2017 sophomore album. Jack Antonoff-produced masterpiece about heartbreak and growing up. "Green Light" and "Liability" showcase her artistic growth.',
                'archivist_note' => 'Universal Music CD with lyric booklet. The production is dense and rewards close listening.',
                'price' => 15.99,
                'category_id' => $pop->id,
                'year' => '2017',
                'label' => 'Universal',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Green Light', 'Sober', 'Homemade Dynamite', 'The Louvre', 'Liability', 'Hard Feelings/Loveless', 'Sober II (Melodrama)', 'Writer in the Dark', 'Supercut', 'Liability (Reprise)', 'Perfect Places'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 7,
                'image' => '/images/figma/cd-lorde.png',
            ],
            [
                'title' => 'DRIP',
                'artist' => 'Joy (Red Velvet)',
                'slug' => 'joy-drip-cd',
                'description' => 'Joy\'s follow-up solo release. More mature sound with R&B influences while maintaining her signature bright vocal tone.',
                'archivist_note' => 'SM Entertainment pressing with exclusive photocards. K-pop collectible in pristine condition.',
                'price' => 22.99,
                'category_id' => $pop->id,
                'year' => '2023',
                'label' => 'SM Entertainment',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['DRIP', 'Reward', 'Vanilla Sky', 'All the Way', 'Midnight Blue'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/cd-joy-redvelvet.png',
            ],
            [
                'title' => 'Io Canto',
                'artist' => 'Laura Pausini',
                'slug' => 'laura-pausini-io-canto-cd',
                'description' => 'Laura Pausini\'s 2006 Italian album. Emotional ballads and pop anthems from one of Italy\'s most beloved vocalists.',
                'archivist_note' => 'Warner Music Italy pressing. Her voice is at its peak - passionate and controlled.',
                'price' => 14.99,
                'category_id' => $pop->id,
                'year' => '2006',
                'label' => 'Warner Music',
                'condition' => 'Near Mint',
                'tracklist' => [
                    'a' => ['Io Canto', 'Sorella Terra', 'Benedetta Passione', 'Un Fatto Ovvio', 'Come Se Non Fosse Stato Mai Amore', 'Il Mio Sbaglio Più Grande', 'Destinazione Paradiso', 'Fidati di Me'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/cd-laura-pausini.png',
            ],
            [
                'title' => 'Primitive',
                'artist' => 'Soulfly',
                'slug' => 'soulfly-primitive-cd',
                'description' => 'Soulfly\'s 2000 album. Heavier and more aggressive than the debut, with Sean Lennon and Tom Araya guest appearances.',
                'archivist_note' => 'Roadrunner Records pressing. The tribal elements are even more pronounced here.',
                'price' => 13.99,
                'category_id' => $rock->id,
                'year' => '2000',
                'label' => 'Roadrunner',
                'condition' => 'Very Good Plus',
                'tracklist' => [
                    'a' => ['Back to the Primitive', 'Pain', 'Bring It', 'Jumpdafuckup', 'Mulambo', 'Son Song', 'Boom', 'Terrorist', 'The Prophet', 'Soulfly II', 'In Memory Of...', 'Flyhigh'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/cd-soulfly.png',
            ],
            [
                'title' => 'Butterfly',
                'artist' => 'Mariah Carey',
                'slug' => 'mariah-carey-butterfly-cd',
                'description' => 'Mariah Carey\'s 1997 album marking her artistic rebirth. Darker, more R&B-influenced sound. "Honey" and "My All" are timeless.',
                'archivist_note' => 'Columbia Records pressing. The hip-hop influences are beautifully integrated with her signature vocals.',
                'price' => 13.99,
                'category_id' => $pop->id,
                'year' => '1997',
                'label' => 'Columbia',
                'condition' => 'Very Good Plus',
                'tracklist' => [
                    'a' => ['Honey', 'Butterfly', 'My All', 'The Roof', 'Fourth of July', 'Breakdown', 'Babydoll', 'Close My Eyes', 'Whenever You Call', 'Fly Away', 'The Beautiful Ones', 'Outside'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 6,
                'image' => '/images/figma/cd-mariah-carey.png',
            ],
            [
                'title' => 'Doggystyle',
                'artist' => 'Snoop Dogg',
                'slug' => 'snoop-dogg-doggystyle-cd',
                'description' => 'Snoop Dogg\'s legendary 1993 debut. Dr. Dre-produced G-funk classic. "Gin and Juice" and "Who Am I? (What\'s My Name?)" defined West Coast rap.',
                'archivist_note' => 'Death Row Records pressing. Essential hip-hop history - the production is immaculate.',
                'price' => 16.99,
                'category_id' => $rock->id,
                'year' => '1993',
                'label' => 'Death Row',
                'condition' => 'Near Mint',
                'tracklist' => [
                    'a' => ['Bathtub', 'G Funk Intro', 'Gin and Juice', 'Tha Shiznit', 'Lodi Dodi', 'Murder Was the Case', 'Serial Killa', 'Who Am I? (What\'s My Name?)', 'For All My Niggaz & Bitches'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 4,
                'image' => '/images/figma/cd-snoop-dogg.png',
            ],
            [
                'title' => 'The World Is Mine',
                'artist' => 'ATEEZ',
                'slug' => 'ateez-world-is-mine-cd',
                'description' => 'ATEEZ\'s explosive album showcasing their theatrical performance style. High-energy tracks perfect for their legendary stage presence.',
                'archivist_note' => 'KQ Entertainment deluxe edition with photocards, stickers, and mini-poster.',
                'price' => 27.99,
                'category_id' => $pop->id,
                'year' => '2023',
                'label' => 'KQ Entertainment',
                'condition' => 'Mint',
                'tracklist' => [
                    'a' => ['Intro', 'Crazy Form', 'Django', 'IT\'s You', 'Wake Up', 'Propaganda', 'Limitless'],
                ],
                'is_featured' => false,
                'is_new_arrival' => false,
                'stock' => 5,
                'image' => '/images/figma/cd-ateez.png',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}
