<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductionSeeder extends Seeder
{
    public function run(): void
    {
        // Categories
        DB::table('categories')->insert([
            ['id' => 1, 'name' => 'Indie & Alternative', 'slug' => 'indie', 'description' => 'Independent and alternative music from groundbreaking artists.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Post-Punk', 'slug' => 'post-punk', 'description' => 'Modern post-punk and experimental rock sounds.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Electronic', 'slug' => 'electronic', 'description' => 'Ambient, techno, and experimental electronic music.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Rock', 'slug' => 'rock', 'description' => 'Classic rock, punk, and metal from the legends.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Folk & Country', 'slug' => 'folk', 'description' => 'Americana, folk, and country from storytelling artists.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Pop', 'slug' => 'pop', 'description' => 'Contemporary pop and art pop releases.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'CD', 'slug' => 'cd', 'description' => 'Compact disc releases and reissues.', 'image' => '/images/Sade_50_R9294-7531.webp', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Products
        DB::table('products')->insert([
            ['id' => 1, 'name' => 'viagr aboys', 'artist' => 'Viagra Boys', 'slug' => 'viagra-boys-viagr-aboys', 'description' => 'The Swedish post-punk provocateurs return with their most ambitious and unhinged album yet. Self-released on their own Shrimptech Enterprises label, this is Viagra Boys at their most raw and inventive.', 'details' => 'Rough Trade Album of the Year 2025. Limited pressing on clear vinyl with red splatter. The production is deliberately lo-fi in places, adding to the album\'s anarchic energy.', 'price' => 32.99, 'image' => '/images/products/viagra-boys-viagr-aboys.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Shrimptech Enterprises', 'condition' => 'Mint', 'tracklist' => '{"a":["Man Made of Meat","The Cognitive Trade-Off Hypothesis","Punk Rock Loser","Troglodyte"],"b":["ADD","Return to Monke","Blue Oyster Cult","Big Boy"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Choke Enough', 'artist' => 'Oklou', 'slug' => 'oklou-choke-enough', 'description' => 'French artist Marylou Mayniel\'s debut album is a stunning work of experimental pop that defies categorization. Ethereal vocals float over intricate electronic production.', 'details' => 'Rough Trade Exclusive pressing on transparent blue vinyl. The album rewards headphone listening - there are layers of detail that reveal themselves over time.', 'price' => 29.99, 'image' => '/images/products/oklou-choke-enough.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Because Music / True Panther', 'condition' => 'Mint', 'tracklist' => '{"a":["galore","choke enough","dire","oblivion"],"b":["gross","appartement","Talisman","so much"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'More', 'artist' => 'Pulp', 'slug' => 'pulp-more', 'description' => 'Pulp\'s first new album in 24 years is a triumphant return. Jarvis Cocker\'s perverse wit is fully intact, now combined with the wisdom that comes from a quarter-century of life experience.', 'details' => 'Gatefold sleeve with printed inner. This is the standard black vinyl edition - the Rough Trade exclusive on gold vinyl sold out immediately.', 'price' => 34.99, 'image' => '/images/products/pulp-more.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Rough Trade Records', 'condition' => 'Mint', 'tracklist' => '{"a":["More","Pulp Fiction","Sorted for E\'s & Wizz","New"],"b":["Common People II","Sheffield","Disco 2000 Again","Finale"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Heavy Metal', 'artist' => 'Cameron Winter', 'slug' => 'cameron-winter-heavy-metal', 'description' => 'Don\'t let the title fool you - this is delicate, introspective folk-rock from Austin songwriter Cameron Winter. His debut album is a gem.', 'details' => 'Pressed on cream colored vinyl. The acoustic guitar tones are warm and present, and his voice cuts through beautifully.', 'price' => 28.99, 'image' => '/images/products/cameron-winter-heavy-metal.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Partisan Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Heavy Metal","Snakes","Coyote","Promise"],"b":["Sunset","River","Texas","End of Days"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Getting Killed', 'artist' => 'Geese', 'slug' => 'geese-getting-killed', 'description' => 'Brooklyn art-rockers Geese prove why they\'re one of the most exciting young bands in America. Angular guitars, propulsive rhythms, and cryptic lyrics.', 'details' => 'Limited clear vinyl edition. The production is intentionally raw, capturing the band\'s live energy.', 'price' => 27.99, 'image' => '/images/products/geese-getting-killed.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Partisan Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Getting Killed","3D Country","Cowboy Nudes","Crusade"],"b":["Undoer","Tomorrow\'s Crusade","2122","Gravity"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'NEVER ENOUGH', 'artist' => 'Turnstile', 'slug' => 'turnstile-never-enough', 'description' => 'Baltimore hardcore heroes Turnstile continue to push boundaries while staying true to their roots. NEVER ENOUGH is their most sonically adventurous work to date.', 'details' => 'Rough Trade Exclusive on yellow vinyl with alternate cover art. The hardcore tracks hit hard, but there\'s also surprising tenderness in the quieter moments.', 'price' => 31.99, 'image' => '/images/products/turnstile-never-enough.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Roadrunner', 'condition' => 'Mint', 'tracklist' => '{"a":["Never Enough","Mystery","Blackout","New Heart Design"],"b":["Fly Again","Alien Love Call","Wild Wrld","Endless"]}', 'in_stock' => 1, 'is_new' => 0, 'stock_quantity' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Forever Howlong', 'artist' => 'Black Country, New Road', 'slug' => 'black-country-new-road-forever-howlong', 'description' => 'The London ensemble\'s third album continues their evolution into one of Britain\'s most adventurous bands. Chamber pop meets post-rock in spectacular fashion.', 'details' => 'Double LP with printed inner sleeves. This pressing captures the band\'s dynamic range beautifully, from whisper-quiet passages to explosive climaxes.', 'price' => 36.99, 'image' => '/images/products/black-country-new-road-forever-howlong.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Ninja Tune', 'condition' => 'Mint', 'tracklist' => '{"a":["Forever Howlong","Up Song","Dancers","Nancy Tries to Take the Night"],"b":["For the Cold Country","Laughing Song","I Won\'t Always Love You","Turbines"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Bloodless', 'artist' => 'Samia', 'slug' => 'samia-bloodless', 'description' => 'New York singer-songwriter Samia delivers her most emotionally devastating album yet. Confessional lyrics meet expansive indie rock production.', 'details' => 'Standard black vinyl with lyrics insert. Her voice has never sounded better, and the band behind her provides the perfect backdrop.', 'price' => 28.99, 'image' => '/images/products/samia-bloodless.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Grand Jury', 'condition' => 'Mint', 'tracklist' => '{"a":["Kill Her Freak Out","Pink Balloon","Mad at Me","Bloodless"],"b":["Sea Lions","Breathing Song","Stay","Honey"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'Foxes In The Snow', 'artist' => 'Jason Isbell', 'slug' => 'jason-isbell-foxes-in-the-snow', 'description' => 'Jason Isbell continues to cement his status as one of America\'s finest songwriters. Foxes In The Snow is intimate, literary, and achingly beautiful.', 'details' => 'Standard black vinyl. The acoustic instrumentation sounds warm and natural - you can hear every finger on every string.', 'price' => 32.99, 'image' => '/images/products/jason-isbell-foxes-in-the-snow.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Southeastern Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Foxes In The Snow","King Of Oklahoma","Miles","If We Were Vampires II"],"b":["Cumberland Gap","White Man\'s World","Hope The High Road","Last of My Kind"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'caroline 2', 'artist' => 'caroline', 'slug' => 'caroline-caroline-2', 'description' => 'The London collective\'s second album expands on their unique blend of post-rock, folk, and minimalism. Patient, immersive, and deeply rewarding.', 'details' => 'Double LP on 180g vinyl from Rough Trade Records. This album demands to be heard in full - it\'s a journey.', 'price' => 34.99, 'image' => '/images/products/caroline-caroline-2.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Rough Trade Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Opening","Nothing","We\'re Gone","Desperately"],"b":["The End","Spiral","Mirror","caroline"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'name' => 'Ego Death At A Bachelorette Party', 'artist' => 'Hayley Williams', 'slug' => 'hayley-williams-ego-death', 'description' => 'The Paramore frontwoman\'s solo work continues to evolve. This album finds her exploring darker electronic textures while maintaining her signature emotional honesty.', 'details' => 'Standard black vinyl with gatefold sleeve. The synth-heavy production translates surprisingly well to vinyl.', 'price' => 29.99, 'image' => '/images/products/hayley-williams-ego-death.jpg', 'category_id' => 6, 'year' => '2025', 'label' => 'Post Atlantic', 'condition' => 'Mint', 'tracklist' => '{"a":["Ego Death","Bachelorette","Simmer","Dead Horse"],"b":["Leave It Alone","Roses","Why We Ever","My Friend"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'name' => 'International', 'artist' => 'Saint Etienne', 'slug' => 'saint-etienne-international', 'description' => 'The beloved British trio return with another collection of immaculate pop songs. International finds them reflecting on memory, place, and the passage of time.', 'details' => 'Heavenly Recordings pressing on sky blue vinyl. The production is crisp and detailed - every synth pad and guitar shimmer comes through clearly.', 'price' => 31.99, 'image' => '/images/products/saint-etienne-international.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Heavenly Recordings', 'condition' => 'Mint', 'tracklist' => '{"a":["International","A World Away","Blue Nile","Summer"],"b":["Departure Lounge","Continental","Night Thoughts","Home"]}', 'in_stock' => 0, 'is_new' => 1, 'stock_quantity' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'name' => 'SABLE, fABLE', 'artist' => 'Bon Iver', 'slug' => 'bon-iver-sable-fable', 'description' => 'Justin Vernon\'s most accessible Bon Iver album finds beauty in simplicity. Stripped-back production lets the songwriting shine through.', 'details' => 'Rough Trade Exclusive on forest green vinyl. The analog warmth of this pressing suits the organic feel of the album perfectly.', 'price' => 33.99, 'image' => '/images/products/bon-iver-sable-fable.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Jagjaguwar', 'condition' => 'Mint', 'tracklist' => '{"a":["SABLE","Things Behind Things Behind Things","SPEYSIDE","What For"],"b":["Vertical","fABLE","Wood Strings","Epilogue"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'name' => 'Euro-Country', 'artist' => 'CMAT', 'slug' => 'cmat-euro-country', 'description' => 'Irish singer CMAT\'s genre-bending second album takes country music on a European tour. Sharp-witted, emotionally resonant, and utterly unique.', 'details' => 'Rough Trade Exclusive on pink vinyl. Her personality shines through on every track - funny, heartbreaking, and always surprising.', 'price' => 28.99, 'image' => '/images/products/cmat-euro-country.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'AWAL', 'condition' => 'Mint', 'tracklist' => '{"a":["California Sober","The Boys of My Youth","Maybe I Was Cruel","Euro-Country"],"b":["Have a Good One","Where Are Your Kids Tonight?","Stay for the Weekend","Nashville"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'name' => 'Love Chant', 'artist' => 'The Lemonheads', 'slug' => 'the-lemonheads-love-chant', 'description' => 'Evan Dando and The Lemonheads return with their first new album in over a decade. The slacker rock charm remains intact, now tempered with hard-won wisdom.', 'details' => 'Fire Records pressing on orange vinyl. Classic Lemonheads sound - jangly guitars, sweet melodies, and Dando\'s unmistakable drawl.', 'price' => 26.99, 'image' => '/images/products/the-lemonheads-love-chant.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Fire Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Love Chant","Drugbuddy","Confetti","Into Your Arms"],"b":["Big Gay Heart","It\'s a Shame About Ray","Ride With Me","Outdoor Type"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'name' => 'Who Let The Dogs Out', 'artist' => 'Lambrini Girls', 'slug' => 'lambrini-girls-who-let-the-dogs-out', 'description' => 'Brighton punk duo Lambrini Girls deliver a ferocious debut. Unapologetically political, wickedly funny, and absolutely vital.', 'details' => 'Neon pink vinyl pressing. Short, sharp, and to the point - this is punk rock at its most immediate and necessary.', 'price' => 25.99, 'image' => '/images/products/lambrini-girls-who-let-the-dogs-out.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'City Slang', 'condition' => 'Mint', 'tracklist' => '{"a":["Big Dick Energy","Company Culture","Filthy Rich Nepo Baby","Cuntology 101"],"b":["Bad Apple","God\'s Country","Working Class Complex","Boys in the Band"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'name' => 'Hot Shock', 'artist' => 'HotWax', 'slug' => 'hotwax-hot-shock', 'description' => 'London trio HotWax bring the grunge revival to the UK with their explosive debut. Heavy riffs, raw vocals, and infectious energy.', 'details' => 'Marathon Artists pressing on splatter vinyl. The guitars are thick and fuzzy, the drums hit hard - a proper rock record.', 'price' => 27.99, 'image' => '/images/products/hotwax-hot-shock.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Marathon Artists', 'condition' => 'Mint', 'tracklist' => '{"a":["Hot Shock","Rip It Up","Spit","Fuse"],"b":["Crash","Louder","Wasted Youth","Burn Out"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'name' => 'Saya', 'artist' => 'Saya Gray', 'slug' => 'saya-gray-saya', 'description' => 'Toronto artist Saya Gray\'s debut is an experimental journey through R&B, jazz, and electronic music. A singular vision from a major new talent.', 'details' => 'Clear vinyl with printed inner sleeve. The bass frequencies are deep and the production is dense with detail.', 'price' => 27.99, 'image' => '/images/products/saya-gray-saya.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Dirty Hit', 'condition' => 'Mint', 'tracklist' => '{"a":["IF IT WASNT 4 U","SHELL OF A MAN","YUNG TURKS","PINK BENZ"],"b":["CIARA","MK ULTRA","SAYA\'S LULLABY","QUI"]}', 'in_stock' => 0, 'is_new' => 0, 'stock_quantity' => 5, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
