<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductionSeeder extends Seeder
{
    public function run(): void
    {
        // Categories (skip if already exist)
        DB::table('categories')->insertOrIgnore([
            ['id' => 1, 'name' => 'Indie & Alternative', 'slug' => 'indie', 'description' => 'Independent and alternative music from groundbreaking artists.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Post-Punk', 'slug' => 'post-punk', 'description' => 'Modern post-punk and experimental rock sounds.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Electronic', 'slug' => 'electronic', 'description' => 'Ambient, techno, and experimental electronic music.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Rock', 'slug' => 'rock', 'description' => 'Classic rock, punk, and metal from the legends.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Folk & Country', 'slug' => 'folk', 'description' => 'Americana, folk, and country from storytelling artists.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Pop', 'slug' => 'pop', 'description' => 'Contemporary pop and art pop releases.', 'image' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'CD', 'slug' => 'cd', 'description' => 'Compact disc releases and reissues.', 'image' => '/images/Sade_50_R9294-7531.webp', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Products (skip if already exist)
        DB::table('products')->insertOrIgnore([
            ['id' => 1, 'title' => 'viagr aboys', 'artist' => 'Viagra Boys', 'slug' => 'viagra-boys-viagr-aboys', 'description' => 'The Swedish post-punk provocateurs return with their most ambitious and unhinged album yet.', 'archivist_note' => 'Rough Trade Album of the Year 2025. Limited pressing on clear vinyl with red splatter.', 'price' => 32.99, 'image' => '/images/products/viagra-boys-viagr-aboys.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Shrimptech Enterprises', 'condition' => 'Mint', 'tracklist' => '{"a":["Man Made of Meat","The Cognitive Trade-Off Hypothesis","Punk Rock Loser","Troglodyte"],"b":["ADD","Return to Monke","Blue Oyster Cult","Big Boy"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'title' => 'Choke Enough', 'artist' => 'Oklou', 'slug' => 'oklou-choke-enough', 'description' => 'French artist Marylou Mayniel\'s debut album is a stunning work of experimental pop.', 'archivist_note' => 'Rough Trade Exclusive pressing on transparent blue vinyl.', 'price' => 29.99, 'image' => '/images/products/oklou-choke-enough.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Because Music / True Panther', 'condition' => 'Mint', 'tracklist' => '{"a":["galore","choke enough","dire","oblivion"],"b":["gross","appartement","Talisman","so much"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'title' => 'More', 'artist' => 'Pulp', 'slug' => 'pulp-more', 'description' => 'Pulp\'s first new album in 24 years is a triumphant return.', 'archivist_note' => 'Gatefold sleeve with printed inner. Standard black vinyl edition.', 'price' => 34.99, 'image' => '/images/products/pulp-more.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Rough Trade Records', 'condition' => 'Mint', 'tracklist' => '{"a":["More","Pulp Fiction","Sorted for E\'s & Wizz","New"],"b":["Common People II","Sheffield","Disco 2000 Again","Finale"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'title' => 'Heavy Metal', 'artist' => 'Cameron Winter', 'slug' => 'cameron-winter-heavy-metal', 'description' => 'Delicate, introspective folk-rock from Austin songwriter Cameron Winter.', 'archivist_note' => 'Pressed on cream colored vinyl.', 'price' => 28.99, 'image' => '/images/products/cameron-winter-heavy-metal.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Partisan Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Heavy Metal","Snakes","Coyote","Promise"],"b":["Sunset","River","Texas","End of Days"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'title' => 'Getting Killed', 'artist' => 'Geese', 'slug' => 'geese-getting-killed', 'description' => 'Brooklyn art-rockers Geese prove why they\'re one of the most exciting young bands.', 'archivist_note' => 'Limited clear vinyl edition.', 'price' => 27.99, 'image' => '/images/products/geese-getting-killed.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Partisan Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Getting Killed","3D Country","Cowboy Nudes","Crusade"],"b":["Undoer","Tomorrow\'s Crusade","2122","Gravity"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'title' => 'NEVER ENOUGH', 'artist' => 'Turnstile', 'slug' => 'turnstile-never-enough', 'description' => 'Baltimore hardcore heroes Turnstile continue to push boundaries.', 'archivist_note' => 'Rough Trade Exclusive on yellow vinyl with alternate cover art.', 'price' => 31.99, 'image' => '/images/products/turnstile-never-enough.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Roadrunner', 'condition' => 'Mint', 'tracklist' => '{"a":["Never Enough","Mystery","Blackout","New Heart Design"],"b":["Fly Again","Alien Love Call","Wild Wrld","Endless"]}', 'is_featured' => 1, 'is_new_arrival' => 0, 'stock' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'title' => 'Forever Howlong', 'artist' => 'Black Country, New Road', 'slug' => 'black-country-new-road-forever-howlong', 'description' => 'The London ensemble\'s third album. Chamber pop meets post-rock.', 'archivist_note' => 'Double LP with printed inner sleeves.', 'price' => 36.99, 'image' => '/images/products/black-country-new-road-forever-howlong.jpg', 'category_id' => 2, 'year' => '2025', 'label' => 'Ninja Tune', 'condition' => 'Mint', 'tracklist' => '{"a":["Forever Howlong","Up Song","Dancers","Nancy Tries to Take the Night"],"b":["For the Cold Country","Laughing Song","I Won\'t Always Love You","Turbines"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'title' => 'Bloodless', 'artist' => 'Samia', 'slug' => 'samia-bloodless', 'description' => 'New York singer-songwriter Samia delivers her most emotionally devastating album.', 'archivist_note' => 'Standard black vinyl with lyrics insert.', 'price' => 28.99, 'image' => '/images/products/samia-bloodless.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Grand Jury', 'condition' => 'Mint', 'tracklist' => '{"a":["Kill Her Freak Out","Pink Balloon","Mad at Me","Bloodless"],"b":["Sea Lions","Breathing Song","Stay","Honey"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'title' => 'Foxes In The Snow', 'artist' => 'Jason Isbell', 'slug' => 'jason-isbell-foxes-in-the-snow', 'description' => 'Jason Isbell continues to cement his status as one of America\'s finest songwriters.', 'archivist_note' => 'Standard black vinyl.', 'price' => 32.99, 'image' => '/images/products/jason-isbell-foxes-in-the-snow.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Southeastern Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Foxes In The Snow","King Of Oklahoma","Miles","If We Were Vampires II"],"b":["Cumberland Gap","White Man\'s World","Hope The High Road","Last of My Kind"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'title' => 'caroline 2', 'artist' => 'caroline', 'slug' => 'caroline-caroline-2', 'description' => 'The London collective\'s second album. Post-rock, folk, and minimalism.', 'archivist_note' => 'Double LP on 180g vinyl from Rough Trade Records.', 'price' => 34.99, 'image' => '/images/products/caroline-caroline-2.jpg', 'category_id' => 1, 'year' => '2025', 'label' => 'Rough Trade Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Opening","Nothing","We\'re Gone","Desperately"],"b":["The End","Spiral","Mirror","caroline"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'title' => 'Ego Death At A Bachelorette Party', 'artist' => 'Hayley Williams', 'slug' => 'hayley-williams-ego-death', 'description' => 'The Paramore frontwoman\'s solo work continues to evolve.', 'archivist_note' => 'Standard black vinyl with gatefold sleeve.', 'price' => 29.99, 'image' => '/images/products/hayley-williams-ego-death.jpg', 'category_id' => 6, 'year' => '2025', 'label' => 'Post Atlantic', 'condition' => 'Mint', 'tracklist' => '{"a":["Ego Death","Bachelorette","Simmer","Dead Horse"],"b":["Leave It Alone","Roses","Why We Ever","My Friend"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'title' => 'International', 'artist' => 'Saint Etienne', 'slug' => 'saint-etienne-international', 'description' => 'The beloved British trio return with another collection of immaculate pop songs.', 'archivist_note' => 'Heavenly Recordings pressing on sky blue vinyl.', 'price' => 31.99, 'image' => '/images/products/saint-etienne-international.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Heavenly Recordings', 'condition' => 'Mint', 'tracklist' => '{"a":["International","A World Away","Blue Nile","Summer"],"b":["Departure Lounge","Continental","Night Thoughts","Home"]}', 'is_featured' => 0, 'is_new_arrival' => 1, 'stock' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'title' => 'SABLE, fABLE', 'artist' => 'Bon Iver', 'slug' => 'bon-iver-sable-fable', 'description' => 'Justin Vernon\'s most accessible Bon Iver album finds beauty in simplicity.', 'archivist_note' => 'Rough Trade Exclusive on forest green vinyl.', 'price' => 33.99, 'image' => '/images/products/bon-iver-sable-fable.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'Jagjaguwar', 'condition' => 'Mint', 'tracklist' => '{"a":["SABLE","Things Behind Things Behind Things","SPEYSIDE","What For"],"b":["Vertical","fABLE","Wood Strings","Epilogue"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'title' => 'Euro-Country', 'artist' => 'CMAT', 'slug' => 'cmat-euro-country', 'description' => 'Irish singer CMAT\'s genre-bending second album takes country music on a European tour.', 'archivist_note' => 'Rough Trade Exclusive on pink vinyl.', 'price' => 28.99, 'image' => '/images/products/cmat-euro-country.jpg', 'category_id' => 5, 'year' => '2025', 'label' => 'AWAL', 'condition' => 'Mint', 'tracklist' => '{"a":["California Sober","The Boys of My Youth","Maybe I Was Cruel","Euro-Country"],"b":["Have a Good One","Where Are Your Kids Tonight?","Stay for the Weekend","Nashville"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'title' => 'Love Chant', 'artist' => 'The Lemonheads', 'slug' => 'the-lemonheads-love-chant', 'description' => 'Evan Dando and The Lemonheads return with their first new album in over a decade.', 'archivist_note' => 'Fire Records pressing on orange vinyl.', 'price' => 26.99, 'image' => '/images/products/the-lemonheads-love-chant.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Fire Records', 'condition' => 'Mint', 'tracklist' => '{"a":["Love Chant","Drugbuddy","Confetti","Into Your Arms"],"b":["Big Gay Heart","It\'s a Shame About Ray","Ride With Me","Outdoor Type"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'title' => 'Who Let The Dogs Out', 'artist' => 'Lambrini Girls', 'slug' => 'lambrini-girls-who-let-the-dogs-out', 'description' => 'Brighton punk duo Lambrini Girls deliver a ferocious debut.', 'archivist_note' => 'Neon pink vinyl pressing.', 'price' => 25.99, 'image' => '/images/products/lambrini-girls-who-let-the-dogs-out.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'City Slang', 'condition' => 'Mint', 'tracklist' => '{"a":["Big Dick Energy","Company Culture","Filthy Rich Nepo Baby","Cuntology 101"],"b":["Bad Apple","God\'s Country","Working Class Complex","Boys in the Band"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'title' => 'Hot Shock', 'artist' => 'HotWax', 'slug' => 'hotwax-hot-shock', 'description' => 'London trio HotWax bring the grunge revival to the UK.', 'archivist_note' => 'Marathon Artists pressing on splatter vinyl.', 'price' => 27.99, 'image' => '/images/products/hotwax-hot-shock.jpg', 'category_id' => 4, 'year' => '2025', 'label' => 'Marathon Artists', 'condition' => 'Mint', 'tracklist' => '{"a":["Hot Shock","Rip It Up","Spit","Fuse"],"b":["Crash","Louder","Wasted Youth","Burn Out"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'title' => 'Saya', 'artist' => 'Saya Gray', 'slug' => 'saya-gray-saya', 'description' => 'Toronto artist Saya Gray\'s debut is an experimental journey through R&B, jazz, and electronic.', 'archivist_note' => 'Clear vinyl with printed inner sleeve.', 'price' => 27.99, 'image' => '/images/products/saya-gray-saya.jpg', 'category_id' => 3, 'year' => '2025', 'label' => 'Dirty Hit', 'condition' => 'Mint', 'tracklist' => '{"a":["IF IT WASNT 4 U","SHELL OF A MAN","YUNG TURKS","PINK BENZ"],"b":["CIARA","MK ULTRA","SAYA\'S LULLABY","QUI"]}', 'is_featured' => 0, 'is_new_arrival' => 0, 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
